package targets

var StartupExamples = []string{
    "Start",
    "Begin",
    "Launch",
    "Initiate",
    "Run",
    "Go",
    "Execute",
    "I'm ready!",
    "Let's go",
    "Let's do this",
    "Let's get started",
    "I am all set",
    "Ready to go",
    "Can't wait",
    "All systems go",
    "Fired up",
    "Let's make it happen",
    "Let's roll",
    "Let's rock",
    "Hit it",
    "Kick it off",
    "Get cracking",
    "Let's boogie",
    "Giddy up",
    "Shoot",
    "Lay it on me",
    "What's up?",
   "Engage",
    "Boot up",
    "Power on",
    "Initialize",
    "Connect",
    "Spawn",
    "Now",
    "On",
    "Do it",
    "Yes",
    "Play",
}
